/*
  Home Control board firmware (common template)
  =============================================

  Every ESP32 runs this same sketch. Everything that differs per board is
  in board_config.h, which the app generates (Settings -> Boards ->
  Download code): board name, relays and their pins, Wi-Fi networks in
  priority order, and the board's cloud sign-in.

  - Joins the highest-priority Wi-Fi in range. Addresses come from the
    Wi-Fi (DHCP), so no static IP is needed on any network.
  - Cloud control through Supabase (cloud.h): the app switches it from
    any network. Relays restore their last state after a power cut.
  - Local HTTP API on port 80 for the same Wi-Fi:
      /status, /on, /off, /toggle (?relay=N)
      /timer?relay&action&seconds[&repeat], /timer/cancel?id= or ?relay=,
      /timers, /timer/clear[?relay=]
  - Up to 10 timers, kept by the board itself.

  Board: ESP32 Dev Module. Libraries: WebSockets (Markus Sattler),
  ArduinoJson.
*/

#include <WiFi.h>
#include <WebServer.h>

#include "board_config.h"  // generated by the app; keep it private

#define CLOUD_RELAYS RELAY_COUNT
#include "cloud.h"


// ============================================================
// RELAYS
// ============================================================

bool relayState[RELAY_COUNT + 1];

void writeRelayPin(uint8_t relay, bool on) {
  bool high = RELAY_ACTIVE_LOW ? !on : on;
  digitalWrite(RELAY_PINS[relay - 1], high ? HIGH : LOW);
}

void setRelay(uint8_t relay, bool on) {

  if (relay < 1 || relay > RELAY_COUNT) {
    return;
  }

  bool changed = relayState[relay] != on;
  relayState[relay] = on;
  writeRelayPin(relay, on);

  if (changed) {
    cloudRelayChanged(relay, on);
  }
}

bool getRelayState(uint8_t relay) {
  return relay >= 1 && relay <= RELAY_COUNT && relayState[relay];
}


// ============================================================
// TIMERS
// ============================================================

#define MAX_TIMERS 10

struct TimerData {
  bool active;
  uint32_t id;
  uint8_t relay;
  bool actionOn;
  bool repeat;
  uint32_t seconds;
  unsigned long scheduledAt;
  unsigned long durationMs;
};

TimerData timers[MAX_TIMERS];
uint32_t nextTimerId = 1;

int countActiveTimers() {
  int count = 0;
  for (int i = 0; i < MAX_TIMERS; i++) {
    if (timers[i].active) count++;
  }
  return count;
}

// Changes whenever a timer is created, cancelled or finishes, so the cloud
// report goes out straight away.
uint32_t cloudTimerSignature() {
  return nextTimerId * 16 + countActiveTimers();
}

int findTimerById(uint32_t id) {
  for (int i = 0; i < MAX_TIMERS; i++) {
    if (timers[i].active && timers[i].id == id) return i;
  }
  return -1;
}

// Returns the new timer's id, or 0 with *error set ("invalid" or "limit").
uint32_t createTimer(uint8_t relay, bool actionOn, uint32_t seconds, bool repeat, const char** error) {

  if (relay < 1 || relay > RELAY_COUNT || seconds < 1 || seconds > 86400) {
    *error = "invalid";
    return 0;
  }

  for (int i = 0; i < MAX_TIMERS; i++) {

    if (timers[i].active) continue;

    TimerData &t = timers[i];
    t.active = true;
    t.id = nextTimerId++;
    if (nextTimerId == 0) nextTimerId = 1;
    t.relay = relay;
    t.actionOn = actionOn;
    t.repeat = repeat;
    t.seconds = seconds;
    t.durationMs = seconds * 1000UL;
    t.scheduledAt = millis();
    return t.id;
  }

  *error = "limit";
  return 0;
}

bool cancelTimerById(uint32_t id) {
  int index = findTimerById(id);
  if (index == -1) return false;
  timers[index].active = false;
  return true;
}

// Returns how many were cancelled, or -1 for an unknown relay.
int cancelTimersOnRelay(uint8_t relay) {

  if (relay < 1 || relay > RELAY_COUNT) {
    return -1;
  }

  int cancelled = 0;
  for (int i = 0; i < MAX_TIMERS; i++) {
    if (timers[i].active && timers[i].relay == relay) {
      timers[i].active = false;
      cancelled++;
    }
  }
  return cancelled;
}

// Runs due timers. Repeating ones keep their rhythm without drifting.
void processTimers() {

  unsigned long now = millis();

  for (int i = 0; i < MAX_TIMERS; i++) {

    TimerData &t = timers[i];
    if (!t.active) continue;

    unsigned long elapsed = now - t.scheduledAt;
    if (elapsed < t.durationMs) continue;

    Serial.printf("Timer %lu: relay %u %s\n", (unsigned long)t.id, t.relay, t.actionOn ? "ON" : "OFF");
    setRelay(t.relay, t.actionOn);

    if (t.repeat) {
      unsigned long periods = elapsed / t.durationMs;
      t.scheduledAt += (periods == 0 ? 1 : periods) * t.durationMs;
    } else {
      t.active = false;
    }
  }
}

// Takes an index, not a TimerData: Arduino puts function prototypes above
// the struct, so a TimerData parameter wouldn't compile.
String timerToJSON(int index) {

  const TimerData &t = timers[index];
  unsigned long elapsed = millis() - t.scheduledAt;
  uint32_t remaining = elapsed < t.durationMs ? (t.durationMs - elapsed + 999) / 1000 : 0;

  String json = "{\"active\":true";
  json += ",\"id\":" + String(t.id);
  json += ",\"relay\":" + String(t.relay);
  json += ",\"action\":\"" + String(t.actionOn ? "on" : "off") + "\"";
  json += ",\"repeat\":" + String(t.repeat ? "true" : "false");
  json += ",\"seconds\":" + String(t.seconds);
  json += ",\"remaining\":" + String(remaining);
  json += "}";
  return json;
}

String timersJSON() {

  String json = "[";
  bool first = true;

  for (int i = 0; i < MAX_TIMERS; i++) {
    if (!timers[i].active) continue;
    if (!first) json += ",";
    json += timerToJSON(i);
    first = false;
  }

  return json + "]";
}


// ============================================================
// STATUS
// ============================================================

String jsonText(const String &value) {

  String out = "\"";
  for (unsigned int i = 0; i < value.length(); i++) {
    char c = value[i];
    if (c == '"' || c == '\\') out += '\\';
    if ((uint8_t)c >= 0x20) out += c;
  }
  return out + "\"";
}

String getStatusJSON() {

  String json = "{\"ok\":true,\"timerApi\":2";
  json += ",\"device\":" + jsonText(BOARD_ID);
  json += ",\"name\":" + jsonText(BOARD_NAME);

  json += ",\"relays\":[";
  for (uint8_t r = 1; r <= RELAY_COUNT; r++) {
    if (r > 1) json += ",";
    json += "{\"relay\":" + String(r) + ",\"power\":\"" + (relayState[r] ? "on" : "off") + "\"}";
  }
  json += "]";

  for (uint8_t r = 1; r <= RELAY_COUNT; r++) {
    json += ",\"relay" + String(r) + "\":" + (relayState[r] ? "true" : "false");
  }

  json += ",\"timers\":" + timersJSON();
  json += ",\"uptime\":" + String(millis() / 1000);
  json += ",\"ip\":" + jsonText(WiFi.localIP().toString());
  json += ",\"ssid\":" + jsonText(WiFi.SSID());
  json += ",\"rssi\":" + String(WiFi.RSSI());
  json += ",\"cloud\":" + jsonText(cloudState);
  json += ",\"acks\":" + cloudAcksJSON();
  json += "}";
  return json;
}


// ============================================================
// WEB SERVER (same Wi-Fi only)
// ============================================================

WebServer server(80);

void addCORS() {
  server.sendHeader("Access-Control-Allow-Origin", "*");
  server.sendHeader("Access-Control-Allow-Methods", "GET, OPTIONS");
  server.sendHeader("Access-Control-Allow-Headers", "*");
}

void sendJSON(int code, const String &json) {
  addCORS();
  server.send(code, "application/json", json);
}

void sendError(int code, const char* error) {
  sendJSON(code, String("{\"ok\":false,\"error\":\"") + error + "\"}");
}

// ?relay=N (defaults to 1). Returns 0 and answers 400 if it's not a relay.
uint8_t relayArg() {
  int relay = server.hasArg("relay") ? server.arg("relay").toInt() : 1;
  if (relay < 1 || relay > RELAY_COUNT) {
    sendError(400, "invalid relay");
    return 0;
  }
  return relay;
}

void handleRoot() {
  addCORS();
  server.send(200, "text/plain", String(BOARD_NAME) + " (" + BOARD_ID + ") is running. See /status.");
}

void handleStatus() {
  sendJSON(200, getStatusJSON());
}

void handleSwitch(int mode) {  // 1 on, 0 off, -1 toggle

  uint8_t relay = relayArg();
  if (!relay) return;

  bool on = mode == -1 ? !relayState[relay] : mode == 1;
  setRelay(relay, on);
  sendJSON(200, "{\"ok\":true,\"relay\":" + String(relay) + ",\"state\":\"" + (on ? "on" : "off") + "\"}");
}

void handleTimer() {

  if (!server.hasArg("action") || !server.hasArg("seconds")) {
    sendError(400, "relay, action and seconds required");
    return;
  }

  uint8_t relay = relayArg();
  if (!relay) return;

  String action = server.arg("action");
  action.toLowerCase();
  if (action != "on" && action != "off") {
    sendError(400, "action must be on or off");
    return;
  }

  String repeatArg = server.arg("repeat");
  repeatArg.toLowerCase();
  bool repeat = repeatArg == "true" || repeatArg == "1";

  const char* error = "invalid";
  uint32_t id = createTimer(relay, action == "on", server.arg("seconds").toInt(), repeat, &error);

  if (!id) {
    if (strcmp(error, "limit") == 0) sendError(409, "maximum 10 timers active");
    else sendError(400, "seconds must be between 1 and 86400");
    return;
  }

  int index = findTimerById(id);
  sendJSON(200, "{\"ok\":true,\"relay\":" + String(relay) + ",\"timer\":" + timerToJSON(index) + "}");
}

void handleTimerCancel() {

  if (server.hasArg("id")) {
    uint32_t id = server.arg("id").toInt();
    if (!cancelTimerById(id)) {
      sendError(404, "timer not found");
      return;
    }
    sendJSON(200, "{\"ok\":true,\"cancelled\":" + String(id) + "}");
    return;
  }

  if (server.hasArg("relay")) {
    uint8_t relay = relayArg();
    if (!relay) return;
    int cancelled = cancelTimersOnRelay(relay);
    sendJSON(200, "{\"ok\":true,\"relay\":" + String(relay) + ",\"cancelled\":" + String(cancelled) + "}");
    return;
  }

  sendError(400, "id or relay required");
}

void handleTimers() {
  sendJSON(200, "{\"ok\":true,\"timers\":" + timersJSON() + "}");
}

// Respects ?relay; without it, clears every relay's timers.
void handleTimerClear() {

  int cancelled = 0;

  if (server.hasArg("relay")) {
    uint8_t relay = relayArg();
    if (!relay) return;
    cancelled = cancelTimersOnRelay(relay);
  } else {
    for (uint8_t r = 1; r <= RELAY_COUNT; r++) cancelled += cancelTimersOnRelay(r);
  }

  sendJSON(200, "{\"ok\":true,\"cancelled\":" + String(cancelled) + "}");
}

void handleOptions() {
  addCORS();
  server.send(204);
}

void setupRoutes() {

  server.on("/", HTTP_GET, handleRoot);
  server.on("/status", HTTP_GET, handleStatus);
  server.on("/on", HTTP_GET, []() { handleSwitch(1); });
  server.on("/off", HTTP_GET, []() { handleSwitch(0); });
  server.on("/toggle", HTTP_GET, []() { handleSwitch(-1); });
  server.on("/timer", HTTP_GET, handleTimer);
  server.on("/timer/cancel", HTTP_GET, handleTimerCancel);
  server.on("/timers", HTTP_GET, handleTimers);
  server.on("/timer/clear", HTTP_GET, handleTimerClear);
  server.on("/timers/clear", HTTP_GET, handleTimerClear);

  server.onNotFound([]() {
    if (server.method() == HTTP_OPTIONS) handleOptions();
    else sendError(404, "not found");
  });
}


// ============================================================
// WI-FI (priority order from the app)
// ============================================================

unsigned long wifiLostAt = 0;
const unsigned long WIFI_RETRY_MS = 10000;

bool tryNetwork(int index, unsigned long timeoutMs) {

  const WifiNetwork &net = WIFI_NETWORKS[index];
  Serial.printf("Wi-Fi %d/%d: %s ", index + 1, WIFI_COUNT, net.ssid);

  WiFi.disconnect(false, false);
  delay(200);
  WiFi.config(INADDR_NONE, INADDR_NONE, INADDR_NONE);  // address from the Wi-Fi (DHCP)
  WiFi.begin(net.ssid, net.password);

  unsigned long start = millis();
  while (WiFi.status() != WL_CONNECTED && millis() - start < timeoutMs) {
    delay(250);
    Serial.print(".");
  }

  if (WiFi.status() == WL_CONNECTED) {
    Serial.printf(" connected, IP %s\n", WiFi.localIP().toString().c_str());
    return true;
  }

  Serial.println(" failed");
  return false;
}

// Joins the highest-priority network that's in range. Networks not seen in
// the scan (e.g. hidden ones) are tried last.
bool connectWiFi() {

  Serial.println("Scanning for Wi-Fi...");
  int found = WiFi.scanNetworks();
  bool visible[WIFI_COUNT];

  for (int i = 0; i < WIFI_COUNT; i++) {
    visible[i] = false;
    for (int j = 0; j < found; j++) {
      if (WiFi.SSID(j) == WIFI_NETWORKS[i].ssid) {
        visible[i] = true;
        break;
      }
    }
  }
  WiFi.scanDelete();

  for (int i = 0; i < WIFI_COUNT; i++) {
    if (visible[i] && tryNetwork(i, 15000)) return true;
  }
  for (int i = 0; i < WIFI_COUNT; i++) {
    if (!visible[i] && tryNetwork(i, 8000)) return true;
  }

  Serial.println("No Wi-Fi network available.");
  return false;
}


// ============================================================
// SETUP / LOOP
// ============================================================

void setup() {

  Serial.begin(115200);
  delay(300);
  Serial.printf("\n%s (%s): %d relay(s), %d Wi-Fi network(s)\n", BOARD_NAME, BOARD_ID, RELAY_COUNT, WIFI_COUNT);

  for (uint8_t r = 1; r <= RELAY_COUNT; r++) {
    pinMode(RELAY_PINS[r - 1], OUTPUT);
    relayState[r] = false;
    writeRelayPin(r, false);
  }

  for (int i = 0; i < MAX_TIMERS; i++) {
    timers[i].active = false;
  }

  cloudBegin();  // restores each relay's last state

  WiFi.mode(WIFI_STA);
  WiFi.setAutoReconnect(true);
  WiFi.persistent(false);
  WiFi.setSleep(false);
  connectWiFi();

  setupRoutes();
  server.begin();
  Serial.println("Ready.");
}

void loop() {

  server.handleClient();
  processTimers();
  cloudLoop();

  // Lost Wi-Fi for 10 s: start again from the highest priority.
  if (WiFi.status() != WL_CONNECTED) {
    if (wifiLostAt == 0) wifiLostAt = millis();
    if (millis() - wifiLostAt >= WIFI_RETRY_MS) {
      connectWiFi();
      wifiLostAt = 0;
    }
  } else {
    wifiLostAt = 0;
  }

  delay(1);
}
